version: '3.7'

services:
  scholarship-service:
    build: .
    ports:
      - 8080:5000
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mariadb-service
  
  postgresql-db-service:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - my-network
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scholarship_db

networks:
  my-network:
    driver: bridge